### ISSUE TITLE
View tab not fully displaying information

### ISSUE THREAD

**Issue by jasmiinee** [AY2425S1-CS2103T-W11-4/tp#156]
![image](https://github.com/user-attachments/assets/68585df2-9b8c-4a87-bfef-ccc7d6578f72)
Since the window cant be adjusted/enlarged, some information gets cutoff which defeats the purpose of viewing client's information in detail, especially when the client has a very long name or email or address. I think would be better if I could adjust the window size or if the text could be wrapped to the next line.

**Comment by JumpyJay** [comment]
i think is same issue as #119
