### ISSUE TITLE
View tab date format

### ISSUE THREAD

**Issue by jasmiinee** [AY2425S1-CS2103T-W11-4/tp#159]
Not sure if it will be more consistent and nicer to format the dates as the ones shown in the person card
![image](https://github.com/user-attachments/assets/3b15eadc-4780-482d-9fb6-e787d0c5909b)
![image](https://github.com/user-attachments/assets/973d3b27-13ec-4d75-914f-97d7f3e83a42)

**Comment by JumpyJay** [comment]
🫠
