### ISSUE TITLE
[PE-D][Tester B] UG add person doesnt show how to prevent duplicate

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-4/tp#207]
![image.png](https://raw.githubusercontent.com/benjiBase/ped/main/files/72040db7-2538-4775-82a0-bfa9811ab201.png)

As shown above, as a user, I would assume i can add any name but

![image.png](https://raw.githubusercontent.com/benjiBase/ped/main/files/1a895e62-5aa5-47e5-90ad-1ceff200ce0e.png)

I need to type to know

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: benjiBase/ped#1

**Comment by jasmiinee** [comment]
update UG under add and edit that name is unique
