### ISSUE TITLE
[PE-D][Tester B] Add person with same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-4/tp#224]
What if in Singapore there exist two customer with exact same name like Tan Wei Jie doesnt have an english name with it. 

How would it get added into the system than?
Name can be duplicated

![image.png](https://raw.githubusercontent.com/benjiBase/ped/main/files/2c6025f1-1359-4efc-b511-dd364407ede3.png)

Maybe can check with other things like phone number etc. 

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: benjiBase/ped#6

**Comment by sarahteonin** [comment]
write in UG big big MUST HAVE UNIQUE NAME
