### ISSUE TITLE
[PE-D][Tester A] Schedule timing limit should be variable based on whoever's using it

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-4/tp#227]
The schedule timing only allows weekdays and from 0900-1600, however there might be some users who might have different timings

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: W3iZhi/ped#7

**Comment by JumpyJay** [comment]
Not too sure what you mean by that, similarly you could say would be good to help 24hr vetenarian track their clients, but that is not our defined target user (9am-4pm physiotherapist clinics)

**Comment by sarahteonin** [comment]
maybe we can define in UG and DG that this is our example working hours, for future implementations can be adjusted according to specific clinic timings
