### ISSUE TITLE
[PE-D][Tester A] ClientInfo names are all in lowercaps

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-4/tp#240]
Due to the add making the name all in lowercaps, inside clientinfo the name is fully in lower caps

![image.png](https://raw.githubusercontent.com/W3iZhi/ped/main/files/2935386e-11bb-4be8-ac7e-0020e3f74556.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: W3iZhi/ped#12

**Comment by sarahteonin** [comment]
flawed issue - stated in ug that this is the case
