### ISSUE TITLE
[PE-D][Tester A] ClientInfo truncates address

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-4/tp#244]
When the client has a long address, clientinfo truncates it

![image.png](https://raw.githubusercontent.com/W3iZhi/ped/main/files/c0c0f054-12de-479d-b233-1bc677dbbb26.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: W3iZhi/ped#15

**Comment by sarahteonin** [comment]
marking this as enhancement because technically user can still view address in mass view (so there is still another way to view the address)
