### ISSUE TITLE
[PE-D][Tester A] Resizing ClientInfo causes issue with the schedule

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-4/tp#247]
When you resize clientinfo, the schedule has an issue where only date is displayed

![image.png](https://raw.githubusercontent.com/W3iZhi/ped/main/files/66525907-6aef-4c64-b122-e0240fc11642.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: W3iZhi/ped#16

**Comment by JumpyJay** [comment]
same as #210
