### ISSUE TITLE
[PE-D][Tester C] Unable to specify reminder for which contact.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-4/tp#258]
Users might want to specify remidners for specific appointment in the future. However, the application is only allowed to set reminders to the person not the appointment. This will fustrate users as they could wait potentially days before they are able to set the intended reminder.

![Screenshot 2024-11-08 at 17.24.29.png](https://raw.githubusercontent.com/stephaneleong/ped/main/files/a43dba85-1bae-43c1-8f82-3dbfbf950fa5.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: stephaneleong/ped#6

**Comment by JumpyJay** [comment]
i don't think can fix this in time, maybe specify in DG under implementations - proposed feature

**Comment by jiayr99** [comment]
Maybe I'll specify that the reminder is for the most upcoming appointment only.

**Comment by jasmiinee** [comment]
possibly can specify that in UG since we cannot change the UI text
![image](https://github.com/user-attachments/assets/0ed94fb5-52ee-4b79-b0cc-481280e6dc53)
